sudo: false
language: python
python:
    - "3.5"
env:
  - TOXENV=py27-dj18
  - TOXENV=py27-dj19
  - TOXENV=py27-dj110
  - TOXENV=py34-dj18
  - TOXENV=py34-dj19
  - TOXENV=py34-dj110
  - TOXENV=py35-dj19
  - TOXENV=py35-dj110
  - TOXENV=coverage
install:
  - pip install tox
  - if [ "$TOXENV" = "coverage" ]; then pip install coveralls; fi
script:
  - export PYTHONPATH=$PYTHONPATH:`pwd`
  - tox
after_success:
  - if [ "$TOXENV" = "coverage" ]; then coveralls; fi
